routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
//    if (\Illuminate\Support\Facades\Auth::check()){
//        return redirect('dashboard');
//    }
    return view('index');
})->name('public.index');

Route::get('/custom-searches', 'PagesController@advancedSearch')->name('public.custom.search');
Route::get('/searches', 'PagesController@search')->name('public.basic.search');

Auth::routes();

Route::group(['prefix' => 'dashboard', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('dashboard');

    //Routes para usuários
    Route::get('/user/index', 'UserController@index')->name('dashboard.user.index');
    Route::get('/user/create', 'UserController@create')->name('dashboard.user.create');
    Route::post('/user/store', 'UserController@store')->name('dashboard.user.store');
//    Route::resource('user', 'UserController', ['only' => [ 'index', 'create', 'store', 'edit', 'update', 'destroy']]);

    //Routes para o objeto de aprend
    Route::get('/object/index', 'LobjectController@index')->name('dashboard.object.index');
    Route::get('/object/create', 'LobjectController@create')->name('dashboard.object.create');
    Route::post('/object/store', 'LobjectController@store')->name('dashboard.object.store');
    Route::resource('object', 'LobjectController',['only' => ['update']]);

    //IF is admin - INDEX
    Route::get('/object/index_admin', 'LobjectController@index')->name('dashboard.object.index_admin');

    //List Objects
    Route::get('object/listObjects/{state_id}', 'LobjectController@listObjects')->name('list.objects')
        ->where('state_id', '[0-9]+');

    Route::get('/back/{state_id}', 'LobjectController@btnBack')
        ->name('btn.back')
        ->where('state_id', '[0-9]+');
    //

    Route::get('object/analyze/{object_id}', 'LobjectController@analyze_object')
        ->name('opt.analyze')
        ->where('object_id', '[0-9]+');

    Route::get('object/to_approve/{object_id}', 'LobjectController@to_approve')
        ->name('opt.to_approve')
        ->where('object_id', '[0-9]+');

    Route::get('object/turn_to_analysis/{object_id}', 'LobjectController@turn_to_analysis')
        ->name('opt.turn_to_analysis')
        ->where('object_id', '[0-9]+');

    Route::post('object/rej_def', 'LobjectController@reject_definitively')->name('opt.rej_def');
    Route::post('object/rej_adj', 'LobjectController@reject_adjustment')->name('opt.rej_adj');

    Route::get('object/delete/{object_id}', 'LobjectController@delete_logically')
        ->name('opt.delete_logically')
        ->where('object_id', '[0-9]+');

    Route::get('object/deleteEver/{object_id}', 'LobjectController@delete_ever')
        ->name('opt.delete_ever')
        ->where('object_id', '[0-9]+');


    Route::get('object/edit/{object_id}', 'LobjectController@edit_object')
        ->name('opt.edit')
        ->where('object_id', '[0-9]+');


    Route::get('/object/viewPendency/{object_id}', 'LobjectController@view_pendency')
        ->name('opt.pend')
        ->where('object_id', '[0-9]+');


});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::resource('accessibility', 'AccessibilityController', ['only' => [ 'index']]);

Route::resource('map', 'MapController', ['only' => [ 'index']]);


//Options for object
Route::get('object/view/{object_id}', 'LobjectController@view_object')
    ->name('opt.view')
    ->where('object_id', '[0-9]+');

resources/views/registers/object/options/both/edit_when_approved.blade.php
@extends('adminlte::page')


@section('content_header')

    <h1>@lang('adminlte::adminlte.edit')</h1>

@endsection

@section('content')

    <div class="container">

        <form method="POST" action="{{ route('object.update', [$object->id]) }}" enctype="multipart/form-data"
              class="form">
            <div class="box-body">

                {{ method_field('PATCH') }}
                {{ csrf_field() }}

                <div class="row">
                    <div class="form-group col-xs-12 col-md-6 pull-left">
                        <label>@lang('adminlte::adminlte.title')</label>

                        <input type="text" name="title" class="form-control"
                               value="{{ old('title') ?? $object->title }}" required>


                        <label>@lang('adminlte::adminlte.author')</label>
                        <input type="text" name="author" class="form-control"
                               value="{{ old('author') ?? $object->author }}" required>

                        <div class="form-group">
                            <label>@lang('adminlte::adminlte.description')</label>
                            <textarea name="description" class="form-control" rows="4">
                                {{ old('description') ?? $object->description }}
                            </textarea>
                        </div>

                        <div class="form-group">
                            <label>@lang('adminlte::adminlte.goal')</label>
                            <textarea name="goal" class="form-control" rows="4">
                                 {{ old('goal') ?? $object->goal }}
                            </textarea>
                        </div>

                        <div class="form-group">
                            <label>@lang('adminlte::adminlte.notes')</label>
                            <textarea name="note" class="form-control" rows="4">
                                {{ old('note') ?? $object->notes }}
                            </textarea>
                        </div>

                        <div class="form-group">
                            <label>@lang('adminlte::adminlte.theme')</label>
                            <textarea name="theme" class="form-control" rows="4">
                                {{ old('theme') ?? $object->theme }}
                            </textarea>
                        </div>

                        <div class="form-group">
                            <label>@lang('adminlte::adminlte.modality')</label>
                            <div class="input-group">
                                <select name="modality" class="form-control">
                                    <option value="{{$modality_obj->id}}">{{$modality_obj->name}}</option>
                                    @foreach(\App\Models\Modality::all()->except($modality_obj->id) as $modality)
                                        <option value="{{$modality->id}}">{{$modality->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label>@lang('adminlte::adminlte.educ_level')</label>

                            <select name="educ_level[]" multiple class="form-control select2"
                                    style="width: 100%" required>
                                @foreach($educ_level_in as $el)
                                    <option selected value="{{$el->id}}">{{$el->level}}</option>
                                @endforeach

                                @foreach($educ_level_out as $el)
                                    <option value="{{$el->id}}"> {{$el->level}}</option>
                                @endforeach
                            </select>

                        </div>


                        <div class="form-group">
                            <label>@lang('adminlte::adminlte.course')</label>
                            <select name="course[]" multiple class="form-control select2" style="width: 100%" required>
                                @foreach($course_in as $co)
                                    <option selected value="{{$co->id}}">{{$co->name}}</option>
                                @endforeach

                                @foreach($course_out as $co)
                                    <option value="{{$co->id}}">{{$co->name}}</option>
                                @endforeach
                            </select>
                        </div>


                        <div class="form-group">
                            <label>@lang('adminlte::adminlte.subject')</label>
                            <select name="subject[]" multiple class="form-control select2" style="width: 100%" required>
                                @foreach($subject_in as $su)
                                    <option selected value="{{$su->id}}">{{$su->name}}</option>
                                @endforeach

                                @foreach($subject_out as $su)
                                    <option value="{{$su->id}}">{{$su->name}}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <label>@lang('adminlte::adminlte.content')</label>
                            <select name="content[]" multiple class="form-control select2" style="width: 100%" required>
                                @foreach($content_in as $cont)
                                    <option selected value="{{$cont->id}}">{{$cont->name}}</option>
                                @endforeach

                                @foreach($content_out as $cont)
                                    <option value="{{$cont->id}}">{{$cont->name}}</option>
                                @endforeach
                            </select>
                        </div>


                        <div class="form-group">
                            <label>@lang('adminlte::adminlte.disability')</label>
                            <select name="disability[]" multiple class="form-control select2" style="width: 100%"
                                    required>
                                @foreach($disability_in as $dis)
                                    <option selected value="{{$dis->id}}">{{$dis->name}}</option>
                                @endforeach

                                @foreach($disability_out as $dis)
                                    <option value="{{$dis->id}}">{{$dis->name}}</option>
                                @endforeach
                            </select>
                        </div>


                        <div class="form-group">
                            <label>@lang('adminlte::adminlte.resource_type')</label>
                            <div class="input-group">
                                <select name="res_type" class="form-control">
                                    <option value="{{$resource_type->id}}">{{$resource_type->name}}</option>
                                    @foreach(\App\Models\ResourceType::all()->except($resource_type->id) as $restype)
                                        <option value="{{$restype->id}}">{{$restype->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>

                        <label>@lang('adminlte::adminlte.language')</label>
                        <select type="text" name="lang" class="form-control">
                            <option value="{{$object->language}}">{{$object->language}}</option>
                            @foreach($langs as $lang)
                                <option>{{$lang}}</option>
                            @endforeach
                        </select>

                        <label>@lang('adminlte::adminlte.country')</label>
                        <select type="text" name="country" class="form-control">
                            <option value="{{$object->country}}">{{$object->country}}</option>
                            @foreach($countries as $country)
                                <option>{{$country}}</option>
                            @endforeach
                        </select>

                        <label>@lang('adminlte::adminlte.keywords')</label>
                        <input type="text" name="keywords" class="form-control"
                               value="{{ old('keywords') ?? $object->key_words }}" required>

                        <label>@lang('adminlte::adminlte.insert_object')</label>
                        <input title="@lang('adminlte::adminlte.insert_object')" value="put" type="file" name="file"
                               class="form-control">
                        <p class="text-muted"> @lang('adminlte::adminlte.registered_object') <i
                                    class="text-yellow"> {{$old_object}}</i></p>
                        <br>


                        <div align="center">
                            <input title=" @lang('adminlte::adminlte.save')" type="submit"
                                   value="@lang('adminlte::adminlte.save')"
                                   class="btn btn-success">


                            <a style="margin-left: 1rem" title="@lang('adminlte::adminlte.cancel')"
                               class="btn btn-danger" href="javascript:history.back()">
                                @lang('adminlte::adminlte.cancel')
                            </a>
                        </div>

                    </div>
                </div>
            </div>
        </form>
        {{--</div>--}}
        {{--</div>--}}
        {{--</div>--}}
    </div>

@endsection

resources/views/registers/object/options/both/edit_when_draft.blade.php
@extends('adminlte::page')


@section('content_header')

    <h1>@lang('adminlte::adminlte.edit')</h1>

@endsection

@section('content')

    <div class="container">

        <form method="POST" action="{{ route('object.update', [$object->id]) }}" enctype="multipart/form-data" id="edit"
              class="form">
            <div class="box-body">

                {{ method_field('PATCH') }}
                {{ csrf_field() }}

                <div class="row">
                    <div class="form-group col-xs-12 col-md-6 pull-left">
                        <label>@lang('adminlte::adminlte.title')</label>

                        <input type="text" name="title" class="form-control"
                               value="{{ old('title') ?? $object->title }}" required>


                        <label>@lang('adminlte::adminlte.author')</label>
                        <input type="text" name="author" class="form-control"
                               value="{{ old('author') ?? $object->author }}" required>

                        <div class="form-group">
                            <label>@lang('adminlte::adminlte.description')</label>
                            <textarea name="description" class="form-control" rows="4">
                                {{ old('description') ?? $object->description }}
                            </textarea>
                        </div>

                        <div class="form-group">
                            <label>@lang('adminlte::adminlte.goal')</label>
                            <textarea name="goal" class="form-control" rows="4">
                                 {{ old('goal') ?? $object->goal }}
                            </textarea>
                        </div>

                        <div class="form-group">
                            <label>@lang('adminlte::adminlte.notes')</label>
                            <textarea name="note" class="form-control" rows="4">
                                {{ old('note') ?? $object->notes }}
                            </textarea>
                        </div>

                        <div class="form-group">
                            <label>@lang('adminlte::adminlte.theme')</label>
                            <textarea name="theme" class="form-control" rows="4">
                                {{ old('theme') ?? $object->theme }}
                            </textarea>
                        </div>

                        <div class="form-group">
                            <label>@lang('adminlte::adminlte.modality')</label>
                            <div class="input-group">
                                <select name="modality" class="form-control">
                                    <option value="{{$modality_obj->id}}">{{$modality_obj->name}}</option>
                                    @foreach(\App\Models\Modality::all()->except($modality_obj->id) as $modality)
                                        <option value="{{$modality->id}}">{{$modality->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label>@lang('adminlte::adminlte.educ_level')</label>

                            <select name="educ_level[]" multiple class="form-control select2"
                                    style="width: 100%" required>
                                @foreach($educ_level_in as $el)
                                    <option selected value="{{$el->id}}">{{$el->level}}</option>
                                @endforeach

                                @foreach($educ_level_out as $el)
                                    <option value="{{$el->id}}"> {{$el->level}}</option>
                                @endforeach
                            </select>

                        </div>


                        <div class="form-group">
                            <label>@lang('adminlte::adminlte.course')</label>
                            <select name="course[]" multiple class="form-control select2" style="width: 100%" required>
                                @foreach($course_in as $co)
                                    <option selected value="{{$co->id}}">{{$co->name}}</option>
                                @endforeach

                                @foreach($course_out as $co)
                                    <option value="{{$co->id}}">{{$co->name}}</option>
                                @endforeach
                            </select>
                        </div>


                        <div class="form-group">
                            <label>@lang('adminlte::adminlte.subject')</label>
                            <select name="subject[]" multiple class="form-control select2" style="width: 100%" required>
                                @foreach($subject_in as $su)
                                    <option selected value="{{$su->id}}">{{$su->name}}</option>
                                @endforeach

                                @foreach($subject_out as $su)
                                    <option value="{{$su->id}}">{{$su->name}}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group">
                            <label>@lang('adminlte::adminlte.content')</label>
                            <select name="content[]" multiple class="form-control select2" style="width: 100%" required>
                                @foreach($content_in as $cont)
                                    <option selected value="{{$cont->id}}">{{$cont->name}}</option>
                                @endforeach

                                @foreach($content_out as $cont)
                                    <option value="{{$cont->id}}">{{$cont->name}}</option>
                                @endforeach
                            </select>
                        </div>


                        <div class="form-group">
                            <label>@lang('adminlte::adminlte.disability')</label>
                            <select name="disability[]" multiple class="form-control select2" style="width: 100%"
                                    required>
                                @foreach($disability_in as $dis)
                                    <option selected value="{{$dis->id}}">{{$dis->name}}</option>
                                @endforeach

                                @foreach($disability_out as $dis)
                                    <option value="{{$dis->id}}">{{$dis->name}}</option>
                                @endforeach
                            </select>
                        </div>


                        <div class="form-group">
                            <label>@lang('adminlte::adminlte.resource_type')</label>
                            <div class="input-group">
                                <select name="res_type" class="form-control">
                                    <option value="{{$resource_type->id}}">{{$resource_type->name}}</option>
                                    @foreach(\App\Models\ResourceType::all()->except($resource_type->id) as $restype)
                                        <option value="{{$restype->id}}">{{$restype->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>

                        <label>@lang('adminlte::adminlte.language')</label>
                        <select type="text" name="lang" class="form-control">
                            <option value="{{$object->language}}">{{$object->language}}</option>
                            @foreach($langs as $lang)
                                <option>{{$lang}}</option>
                            @endforeach
                        </select>

                        <label>@lang('adminlte::adminlte.country')</label>
                        <select type="text" name="country" class="form-control">
                            <option value="{{$object->country}}">{{$object->country}}</option>
                            @foreach($countries as $country)
                                <option>{{$country}}</option>
                            @endforeach
                        </select>

                        <label>@lang('adminlte::adminlte.keywords')</label>
                        <input type="text" name="keywords" class="form-control"
                               value="{{ old('keywords') ?? $object->key_words }}" required>

                        <div class="form-group">
                            <label>@lang('adminlte::adminlte.insert_object')</label>
                            <input title=" @lang('adminlte::adminlte.insert_object')" value="put" type="file" name="file" class="form-control">
                            <p class="text-muted"> @lang('adminlte::adminlte.registered_object') <i class="text-yellow"> {{$old_object}}</i></p>
                        </div>


                        <div class="form-group">
                            <div class="radio ">
                                <label>
                                    <input type="radio" name="option" value="0" checked>
                                    <i class="fa fa-fw  fa-save"></i>
                                    @lang('adminlte::adminlte.save_as_draft')
                                </label>
                            </div>
                            <div class="radio ">
                                <label>
                                    <input type="radio" name="option" value="1">
                                    <i class="fa fa-fw  fa-send-o"></i>
                                    @lang('adminlte::adminlte.send_to_analyze')
                                </label>
                            </div>
                        </div>

                        <div align="center">
                            <input title=" @lang('adminlte::adminlte.save')" type="submit"
                                   value="@lang('adminlte::adminlte.save')"
                                   class="btn btn-success">


                            <a style="margin-left: 1rem" title="@lang('adminlte::adminlte.cancel')"
                               class="btn btn-danger" href="javascript:history.back()">
                                @lang('adminlte::adminlte.cancel')
                            </a>
                        </div>


                    </div>
                </div>
            </div>
        </form>

    </div>

@endsection

resources/views/registers/object/options/both/view_object.blade.php
@extends('adminlte::page')

@section('content_header')
    <h1>@lang('adminlte::adminlte.details_of_object')</h1>
@endsection

@section('content')

    @include('registers.object.options.both.view_object_partial')


@endsection