routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
//    if (\Illuminate\Support\Facades\Auth::check()){
//        return redirect('dashboard');
//    }
    return view('index');
})->name('public.index');

Route::get('/custom-searches', 'PagesController@advancedSearch')->name('public.custom.search');
Route::get('/searches', 'PagesController@search')->name('public.basic.search');

Auth::routes();

Route::group(['prefix' => 'dashboard', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('dashboard');

    //Routes para usuários
    Route::get('/user/index', 'UserController@index')->name('dashboard.user.index');
    Route::get('/user/create', 'UserController@create')->name('dashboard.user.create');
    Route::post('/user/store', 'UserController@store')->name('dashboard.user.store');
//    Route::resource('user', 'UserController', ['only' => [ 'index', 'create', 'store', 'edit', 'update', 'destroy']]);

    //Routes para o objeto de aprend
    Route::get('/object/index', 'LobjectController@index')->name('dashboard.object.index');
    Route::get('/object/create', 'LobjectController@create')->name('dashboard.object.create');
    Route::post('/object/store', 'LobjectController@store')->name('dashboard.object.store');
    Route::resource('object', 'LobjectController',['only' => ['update']]);

    //IF is admin - INDEX
    Route::get('/object/index_admin', 'LobjectController@index')->name('dashboard.object.index_admin');

    //List Objects
    Route::get('object/listObjects/{state_id}', 'LobjectController@listObjects')->name('list.objects')
        ->where('state_id', '[0-9]+');

    Route::get('/back/{state_id}', 'LobjectController@btnBack')
        ->name('btn.back')
        ->where('state_id', '[0-9]+');
    //

    Route::get('object/analyze/{object_id}', 'LobjectController@analyze_object')
        ->name('opt.analyze')
        ->where('object_id', '[0-9]+');

    Route::get('object/to_approve/{object_id}', 'LobjectController@to_approve')
        ->name('opt.to_approve')
        ->where('object_id', '[0-9]+');

    Route::get('object/turn_to_analysis/{object_id}', 'LobjectController@turn_to_analysis')
        ->name('opt.turn_to_analysis')
        ->where('object_id', '[0-9]+');

    Route::post('object/rej_def', 'LobjectController@reject_definitively')->name('opt.rej_def');
    Route::post('object/rej_adj', 'LobjectController@reject_adjustment')->name('opt.rej_adj');

    Route::get('object/delete/{object_id}', 'LobjectController@delete_logically')
        ->name('opt.delete_logically')
        ->where('object_id', '[0-9]+');

    Route::get('object/deleteEver/{object_id}', 'LobjectController@delete_ever')
        ->name('opt.delete_ever')
        ->where('object_id', '[0-9]+');


    Route::get('object/edit/{object_id}', 'LobjectController@edit_object')
        ->name('opt.edit')
        ->where('object_id', '[0-9]+');


    Route::get('/object/viewPendency/{object_id}', 'LobjectController@view_pendency')
        ->name('opt.pend')
        ->where('object_id', '[0-9]+');


});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::resource('accessibility', 'AccessibilityController', ['only' => [ 'index']]);

Route::resource('map', 'MapController', ['only' => [ 'index']]);


//Options for object
Route::get('object/view/{object_id}', 'LobjectController@view_object')
    ->name('opt.view')
    ->where('object_id', '[0-9]+');

resources/views/registers/object/collaborator/approved.blade.php
@extends('adminlte::page')

@section('title', config('app.name') )

@section('content_header')
    <h1>@lang('adminlte::adminlte.object.opt_approved')</h1>

@stop

@section('content')
    <div class="box">
        <div class="box-header with-border">

            <div class="box-body">

                {{-- <p>{{$objects}}</p>--}}

                {{--@foreach($all_objects as $all_object)
                    <p>{{$all_object->object_id }} - - - {{ $all_object->order }} - - - {{$all_object->state_id}}</p>
                @endforeach--}}

                @if(!$objects->isEmpty())

                    <div class="table-responsive">

                        <table class="table">

                            <thead>
                            <tr>
                                <th>@lang('adminlte::adminlte.name')</th>
                                <th>@lang('adminlte::adminlte.format')</th>
                                <th>@lang('adminlte::adminlte.size')</th>
                                <th>@lang('adminlte::adminlte.approved_in')</th>
                                <th>@lang('adminlte::adminlte.actions')</th>

                            </tr>
                            </thead>

                            <tbody>
                            @foreach($objects as $object)
                                <tr>
                                    <td>{{ $object->title }}</td>
                                    <td>{{ $object->format }}</td>
                                    <td>{{ $object->size }}</td>
                                    <td><?php echo date('d/m/Y - H:i:s', strtotime( $object->los->order )); ?></td>
                                    <td>
                                        <a href="{{ route('opt.view', ['object_id' => $object->los->lobject_id]) }}"
                                           title="@lang('adminlte::adminlte.view')" class="btn btn-default"><i class="fa fa-fw fa-eye"></i>
                                        </a>

                                    </td>

                                </tr>
                            @endforeach
                            </tbody>


                        </table>
                    </div>
                @else

                    <div class="callout callout-warning">
                        <h4>@lang('adminlte::adminlte.object.none')</h4>
                    </div>

                @endif
            </div>
            <!-- /.row -->
        </div>
        <!-- /.box-footer -->
    </div>
    {{--
        @push('menu-items')
            @each('adminlte::partials.menu-item', config('menu'), 'item')
        @endpush--}}
@stop

@section('adminlte_js')
    <script src="{{ asset('vendor/adminlte/dist/js/adminlte.min.js') }}"></script>
    @stack('js')
    @yield('js')
@stop

resources/views/registers/object/collaborator/awaiting_review.blade.php
@extends('adminlte::page')

@section('title', config('app.name') )

@section('content_header')
    <h1>@lang('adminlte::adminlte.object.opt_waiting_rev')</h1>

@stop

@section('content')
    <div class="box">
        <div class="box-header with-border">

            <div class="box-body">

                @if(!$objects->isEmpty())

                    <div class="table-responsive">

                        <table class="table">

                            <thead>
                            <tr>
                                <th>@lang('adminlte::adminlte.name')</th>
                                <th>@lang('adminlte::adminlte.format')</th>
                                <th>@lang('adminlte::adminlte.size')</th>
                                <th>@lang('adminlte::adminlte.actions')</th>

                            </tr>
                            </thead>

                            <tbody>
                            @foreach($objects as $object)
                                <tr>
                                    <td>{{ $object->title }}</td>
                                    <td>{{ $object->format }}</td>
                                    <td>{{ $object->size }}</td>

                                    <td>
                                        <a href="{{ route('opt.view', ['object_id' => $object->los->lobject_id]) }}"
                                           title="@lang('adminlte::adminlte.view')" class="btn btn-default"><i class="fa fa-fw fa-eye"></i>
                                        </a>
                                    </td>

                                </tr>
                            @endforeach
                            </tbody>
                        </table>

                        {{ $objects->links() }}

                    </div>
                @else

                    <div class="callout callout-warning">
                        <h4>@lang('adminlte::adminlte.object.none')</h4>
                    </div>

                @endif
            </div>
            <!-- /.row -->
        </div>
        <!-- /.box-footer -->
    </div>
    {{--
        @push('menu-items')
            @each('adminlte::partials.menu-item', config('menu'), 'item')
        @endpush--}}
@stop

@section('adminlte_js')
    <script src="{{ asset('vendor/adminlte/dist/js/adminlte.min.js') }}"></script>
    @stack('js')
    @yield('js')
@stop

resources/views/registers/object/collaborator/draft.blade.php
@extends('adminlte::page')

@section('title', config('app.name') )

@section('content_header')
    <h1>@lang('adminlte::adminlte.object.opt_draft')</h1>

@stop

@section('content')
    <div class="box">
        <div class="box-header with-border">

            <div class="box-body">

                @if(!$objects->isEmpty())

                    <div class="table-responsive">

                        <table class="table">

                            <thead>
                            <tr>
                                <th>@lang('adminlte::adminlte.name')</th>
                                <th>@lang('adminlte::adminlte.format')</th>
                                <th>@lang('adminlte::adminlte.size')</th>
                                <th>@lang('adminlte::adminlte.created')</th>
                                <th>@lang('adminlte::adminlte.actions')</th>
                            </tr>
                            </thead>

                            <tbody>
                            @foreach($objects as $object)
                                <tr>
                                    <td>{{ $object->title }}</td>
                                    <td>{{ $object->format }}</td>
                                    <td>{{ $object->size }}</td>
                                    <td><?php echo date('d/m/Y - H:i:s', strtotime( $object->los->order )); ?></td>
                                    <td>
                                        <a href="{{ route('opt.view', ['object_id' => $object->los->lobject_id]) }}"
                                           title="@lang('adminlte::adminlte.view')" class="btn btn-default"><i class="fa fa-fw fa-eye"></i>
                                        </a>
                                        <a href="{{ route('opt.edit', ['object_id' => $object->los->lobject_id]) }}"
                                           title="@lang('adminlte::adminlte.edit')" class="btn btn-default" style="margin-left: 1rem">
                                            <i class="fa fa-fw fa-pencil"></i>
                                        </a>
                                       {{-- <a title="Excluir" class="btn btn-danger" style="margin-left: 1rem"
                                           data-toggle="modal" data-target="#modal-del-def">
                                            <i class="fa fa-fw fa-trash-o"></i>
                                        </a>--}}
                                        <a href="{{route('opt.delete_ever',['object_id' => $object->los->lobject_id]) }}"
                                           title="@lang('adminlte::adminlte.delete_ever')" class="btn btn-danger" style="margin-left: 1rem">
                                            <i class="fa fa-fw fa-trash-o"></i>
                                        </a>

                                    </td>
                                </tr>

                                {{--Excluir Definitivamente o Objeto--}}
                                {{--<div class="modal modal-danger fade in" id="modal-del-def" style="display: none;">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal"
                                                        aria-label="Close">
                                                    <span aria-hidden="true">×</span></button>
                                                <h4 class="modal-title">Excluir Objeto</h4>
                                            </div>
                                            <div class="modal-body">

                                                <p>Ao clicar em excluir, você estará concordando em deletar o
                                                    objeto "{{$object->title}}" definitivamente da Base de Dados do ROAC.</p>
                                                <p>Id: {{$object->los->lobject_id}}</p>

                                            </div>
                                            <div class="modal-footer">
                                                --}}{{--Delte Object--}}{{--

                                                <form id="formDeleteObject"
                                                      action="{{ route('object.destroy', [$object->los->lobject_id]) }}"
                                                      method="POST">

                                                    {{ csrf_field() }}
                                                    {{ method_field('DELETE') }}

                                                    <br>

                                                    <button type="button" class="btn btn-outline pull-left"
                                                            data-dismiss="modal">Fechar
                                                    </button>

                                                    <input type="submit" title="Excluir"
                                                           class="btn btn-outline pull-right"
                                                           style="margin-left: 1rem"
                                                           value="Excluir">

                                                </form>
                                            </div>
                                        </div>
                                        <!-- /.modal-content -->
                                    </div>
                                    <!-- /.modal-dialog -->
                                </div>--}}


                            @endforeach
                            </tbody>


                        </table>
                    </div>
                @else

                    <div class="callout callout-warning">
                        <h4>@lang('adminlte::adminlte.object.none')</h4>
                    </div>

                @endif
            </div>
            <!-- /.row -->
        </div>
        <!-- /.box-footer -->
    </div>
    {{--
        @push('menu-items')
            @each('adminlte::partials.menu-item', config('menu'), 'item')
        @endpush--}}
@stop

@section('adminlte_js')
    <script src="{{ asset('vendor/adminlte/dist/js/adminlte.min.js') }}"></script>
    @stack('js')
    @yield('js')
@stop

resources/views/registers/object/collaborator/rejected.blade.php
@extends('adminlte::page')

@section('title', config('app.name') )

@section('content_header')
    <h1>@lang('adminlte::adminlte.object.opt_rej_ever')</h1>

@stop

@section('content')
    <div class="box">
        <div class="box-header with-border">

            <div class="box-body">

                @if(!$objects->isEmpty())

                    <div class="table-responsive">

                        <table class="table">

                            <thead>
                            <tr>


                                <th>@lang('adminlte::adminlte.name')</th>
                                <th>@lang('adminlte::adminlte.format')</th>
                                <th>@lang('adminlte::adminlte.size')</th>
                                <th>@lang('adminlte::adminlte.motivation')</th>
                                <th>@lang('adminlte::adminlte.actions')</th>

                            </tr>
                            </thead>

                            <tbody>
                            @foreach($objects as $object)

                                <tr>
                                    <td>{{ $object->title }}</td>
                                    <td>{{ $object->format }}</td>
                                    <td>{{ $object->size }}</td>
                                    {{--<td>{{ $object->order }}</td>--}}
                                    <td style="width: 30%">{{ $object->reason_of_rejection }}</td>
                                    <td>
                                        <a href="{{ route('opt.view', ['object_id' => $object->los->lobject_id]) }}"
                                           title="@lang('adminlte::adminlte.view')" class="btn btn-default"><i class="fa fa-fw fa-eye"></i>
                                        </a>
                                        {{--<a title="Ver motivação" class="btn btn-default" style="margin-left: 1rem"
                                           data-toggle="modal" data-target="#modal-obj-rej">
                                            <i class="fa fa-fw fa-commenting-o"></i>
                                        </a>--}}

                                    </td>
                                </tr>


                                {{--Reason for rejection of Object--}}
                               {{-- <div class="modal fade in" id="modal-obj-rej" style="display: none;">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">×</span></button>
                                                <h4 class="modal-title">Objeto Rejeitado</h4>
                                            </div>
                                            <div class="modal-body">
                                                <p>{{$object->title}}</p>
                                                <p>{{$object->reason_of_rejection}}</p>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Fechar</button>
                                            </div>
                                        </div>
                                        <!-- /.modal-content -->
                                    </div>
                                    <!-- /.modal-dialog -->
                                </div>--}}



                            @endforeach
                            </tbody>
                        </table>
                    </div>
                @else

                    <div class="callout callout-warning">
                        <h4>@lang('adminlte::adminlte.object.none')</h4>
                    </div>

                @endif

            </div>
            <!-- /.row -->
        </div>
        <!-- /.box-footer -->
    </div>



@stop

@section('adminlte_js')
    <script src="{{ asset('vendor/adminlte/dist/js/adminlte.min.js') }}"></script>
    @stack('js')
    @yield('js')
@stop

resources/views/registers/object/collaborator/rejected_with_pendency.blade.php
@extends('adminlte::page')

@section('title', config('app.name') )

@section('content_header')
    <h1>@lang('adminlte::adminlte.object.opt_rej_adj')</h1>

@stop

@section('content')
    <div class="box">
        <div class="box-header with-border">

            <div class="box-body">

                @if(!$objects->isEmpty())

                    <div class="table-responsive">

                        <table class="table">

                            <thead>
                            <tr>

                                <th>@lang('adminlte::adminlte.name')</th>
                                <th>@lang('adminlte::adminlte.format')</th>
                                <th>@lang('adminlte::adminlte.size')</th>
                                <th>@lang('adminlte::adminlte.latest_review')</th>
                                <th>@lang('adminlte::adminlte.actions')</th>


                            </tr>
                            </thead>

                            <tbody>
                            @foreach($objects as $object)
                                <tr>
                                    <td>{{ $object->title }}</td>
                                    <td>{{ $object->format }}</td>
                                    <td>{{ $object->size }}</td>
                                    <td><?php echo date('d/m/Y - H:i:s', strtotime( $object->los->order )); ?></td>
                                    <td>

                                        <a href="{{ route('opt.view', ['object_id' => $object->los->lobject_id]) }}"
                                           title="@lang('adminlte::adminlte.view')" class="btn btn-default" style="margin-left: 1rem">
                                            <i
                                                    class="fa fa-fw fa-eye"></i>
                                        </a>
                                        <a href="{{route('opt.pend', ['object_id' => $object->los->lobject_id]) }}"
                                           title="@lang('adminlte::adminlte.view_pendency')" class="btn btn-default" style="margin-left: 1rem">
                                            <i class="fa fa-fw fa-commenting-o"></i>
                                        </a>

                                        <a href="{{ route('opt.edit', ['object_id' => $object->los->lobject_id]) }}"
                                           title="@lang('adminlte::adminlte.edit')" class="btn btn-default" style="margin-left: 1rem">
                                            <i class="fa fa-fw fa-pencil"></i>
                                        </a>


                                    </td>

                                </tr>

                            @endforeach
                            </tbody>


                        </table>
                    </div>
                @else

                    <div class="callout callout-warning">
                        <h4>@lang('adminlte::adminlte.object.none')</h4>
                    </div>

                @endif

            </div>
            <!-- /.row -->
        </div>
        <!-- /.box-footer -->
    </div>
    {{--
        @push('menu-items')
            @each('adminlte::partials.menu-item', config('menu'), 'item')
        @endpush--}}
@stop

@section('adminlte_js')
    <script src="{{ asset('vendor/adminlte/dist/js/adminlte.min.js') }}"></script>
    @stack('js')
    @yield('js')
@stop